// generated by tools/gen_assets.py - do not edit
#pragma once
#define MASK_KIND_TILE    0
#define MASK_KIND_LAPTOP  1
#define MASK_KIND_DESKTOP 2
#define MASK_KIND_DOT     3
#define MASK_KIND_DOTCUT  4
#define MASK_KIND_COUNT   5
#define MASK_RES_BASE     1000
#define MASK_RES_ID(kind, idx) (MASK_RES_BASE + (kind) * 100 + (idx))
#define MASK_SIZE_COUNT   17
#ifndef RC_INVOKED
static const int kMaskSizes[MASK_SIZE_COUNT] = { 16, 20, 24, 28, 30, 32, 36, 40, 48, 56, 64, 72, 80, 96, 128, 192, 256 };
#endif
